### ISSUE TITLE
chore: Test Container 설정

### ISSUE THREAD

**Issue by Borieya0619** [hana-runner/hana-v-backend#18]
## 📍 제목
Test Container 설정

## 📃 목적
테스트 환경의 멱등성을 제공 받기 위해 Test Container를 활용하여 통합 테스팅 환경을 구축합니다. 

## 📋 내용

- Test Container 의존성 추가
- 테스트 모듈에 TestContainer를 위한 설정 작성

## ❗ 체크리스트

- [ ] 문제를 명확히 파악하였습니다.
- [ ] 문제를 재현할 수 있습니다.
- [ ] 문제를 해결하기 위한 접근 방식을 검토하였습니다.
- [ ] 관련 문서를 검토하였습니다.
- [ ] 이슈 템플릿 형식에 맞게 작성하였습니다.
- [ ] 관련 이슈, 기여자, 라벨을 지정하였습니다.

**Comment by pocj8ur4in** [comment]
'chore: docker-compose 생성'으로 통합
